### ISSUE TITLE
symbol_definitions, symbol_references, symbol_doccomments undefined error

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#175]
Hello @MaximeChretien 

An error found in the Elixir server logs...
You may harden your code to avoid ending up with undefined variables in case there's something wrong in the database or when a client requests a symbol that doesn't exist...

----

KeyError
Python 3.6.9: /usr/bin/python3
Wed Jul  8 06:24:20 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/local/elixir/http/web.py in <module>()
  327     data['title'] = ident+' identifier - '+title_suffix
  328
  329     symbol_definitions, symbol_references, symbol_doccomments = query('ident', tag, ident, family)
  330
  331     print('<div class="lxrident">')
symbol_definitions undefined
symbol_references undefined
symbol_doccomments undefined
query = <function query>
tag = 'v4.19.115'
ident = 'alloc_task_struct_node'
family = 'c'

 /usr/local/elixir/query.py in query(cmd='ident', *args=('v4.19.115', 'alloc_task_struct_node', 'c'))
  230             return get_idents_comps(version, ident)
  231         else:
  232             return get_idents_defs(version, ident, family)
  233
  234     else:
global get_idents_defs = <function get_idents_defs>
version = 'v4.19.115'
ident = 'alloc_task_struct_node'
family = 'c'

 /usr/local/elixir/query.py in get_idents_defs(version='v4.19.115', ident='alloc_task_struct_node', family='c')
  343         while def_idx == file_idx:
  344             if (def_family == family or family == 'A'
  345                 or lib.compatibleMacro(macros_this_ident, family)):
  346                 dBuf.append((file_path, def_type, def_line))
  347             def_idx, def_type, def_line, def_family = next(defs_this_ident)
global lib = <module 'lib' from '/usr/local/elixir/http/../lib.py'>
lib.compatibleMacro = <function compatibleMacro>
macros_this_ident = ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', ...]
family = 'c'

 /usr/local/elixir/lib.py in compatibleMacro(macro_family=['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', ...], requested_family='c')
  234     result = False
  235     for item in macro_family:
  236         item += 'M'
  237         result = result or item in compatibility_list[requested_family]
  238     return result
result = False
item = 'CM'
global compatibility_list = {'C': ['C', 'K'], 'D': ['D', 'CM'], 'K': ['K'], 'M': ['K']}
requested_family = 'c'
KeyError: 'c'
    __cause__ = None
    __class__ = <class 'KeyError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of KeyError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of KeyError object>
    __doc__ = 'Mapping key not found.'
    __eq__ = <method-wrapper '__eq__' of KeyError object>
    __format__ = <built-in method __format__ of KeyError object>
    __ge__ = <method-wrapper '__ge__' of KeyError object>
    __getattribute__ = <method-wrapper '__getattribute__' of KeyError object>
    __gt__ = <method-wrapper '__gt__' of KeyError object>
    __hash__ = <method-wrapper '__hash__' of KeyError object>
    __init__ = <method-wrapper '__init__' of KeyError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of KeyError object>
    __lt__ = <method-wrapper '__lt__' of KeyError object>
    __ne__ = <method-wrapper '__ne__' of KeyError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of KeyError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of KeyError object>
    __repr__ = <method-wrapper '__repr__' of KeyError object>
    __setattr__ = <method-wrapper '__setattr__' of KeyError object>
    __setstate__ = <built-in method __setstate__ of KeyError object>
    __sizeof__ = <built-in method __sizeof__ of KeyError object>
    __str__ = <method-wrapper '__str__' of KeyError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('c',)
    with_traceback = <built-in method with_traceback of KeyError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/elixir/http/web.py", line 329, in <module>
    symbol_definitions, symbol_references, symbol_doccomments = query('ident', tag, ident, family)
  File "/usr/local/elixir/http/../query.py", line 232, in query
    return get_idents_defs(version, ident, family)
  File "/usr/local/elixir/http/../query.py", line 345, in get_idents_defs
    or lib.compatibleMacro(macros_this_ident, family)):
  File "/usr/local/elixir/http/../lib.py", line 237, in compatibleMacro
    result = result or item in compatibility_list[requested_family]
KeyError: 'c'

**Comment by michaelopdenacker** [comment]
Here's another case when this happens:
query = <function query>
tag = 'v4.19.115'
ident = 'kmem_cache_alloc_node'
family = 'c'

**Comment by michaelopdenacker** [comment]
Another one:
query = <function query>
tag = 'v4.9.111'
ident = 'of_match_ptr'
family = 'c'
