### ISSUE TITLE
no result when running query.py

### ISSUE THREAD

**Issue by sk-buff** [bootlin/elixir#181]
HI all,

I'm following the instructions in README of commit c04e9e3. After the creation of database by running update.py, I met a problem when running query.py. When I ran the first query test case `./query.py v4.10 ident raw_spin_unlock_irq C`, the result displayed in my terminal is the following:
```
Symbol Definitions:

Symbol References:

Documented in:
```
where no results are found. But the second test case `./query.py v4.10 file /kernel/sched/clock.c` can return the content of the file correctly. I would be grateful if someone can help me solve this problem.

**Comment by cloudburst** [comment]
As far as I can tell this is related to the following error (but I don't know the solution):

```
mod_wsgi (pid=11111): Exception occurred processing WSGI script '/usr/local/elixir/api/api.py'.                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                           
  File "falcon/api.py", line 274, in falcon.api.API.__call__                                                                                                                                                 
  File "falcon/api.py", line 269, in falcon.api.API.__call__                                                                                                                                                 
  File "/usr/local/elixir/api/api.py", line 45, in on_get                                                                                                                                                    
    query = build_query(req.env, project)                                                                                                                                                                    
  File "/usr/local/elixir/api/api.py", line 40, in build_query                                                                                                                                               
    import query                                                                                                                                                                                             
  File "/usr/local/elixir/api/../query.py", line 28, in <module>                                                                                                                                             
    dts_comp_support = int(script('dts-comp'))                                                                                                                                                               
ValueError: invalid literal for int() with base 10: b"/usr/local/elixir/script.sh: Can't find repository\\n"
```

**Comment by cxw42** [comment]
- I see that commit is from Aug. 2020 --- have you tried with `master`?
- Do the tests pass?  (Do the `before_install` and `script` steps in [`.travis.yml`](https://github.com/bootlin/elixir/blob/master/.travis.yml))

**Comment by cloudburst** [comment]
I had the same problem with `master` but your comment provided the solution.  After running `prove -v` I noticed the indexing was failing.  It turned out to be a problem with using the ctags in the ubuntu repo.

I fixed by using the deb in the Travis file `https://bootlin.com/pub/elixir/universal-ctags_0+git20200526-0ubuntu1_amd64.deb`.  Then I deleted the database and did a full reindex with `./update.py`  Now the query works.  Thank you.

**Comment by cxw42** [comment]
Great news!  Would you please close this issue, then?  Thank you!

**Comment by fstachura** [comment]
Elixir has been refactored recently. README from master should work at least until the update step. ctags from Debian 12 should mostly work, although we recommend the Docker setup now.
