### ISSUE TITLE
.get_families undefined error in web.py

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/elixir#200]
Hello,
I've found this issue in the http server logs...

I hope the below details help...
Cheers,
Michael
----

```
ValueError
Python 3.8.5: /usr/bin/python3
Mon Oct 26 01:14:42 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/local/elixir/http/web.py in <module>
  213             lines += query('dir', tag, path)
  214         elif type == 'blob':
  215             code = query('file', tag, path)
  216     else:
  217         print('<div class="lxrerror"><h2>This file does not exist.</h2></div>')
code undefined
query = <function query>
tag = 'v4.9.81'
path = '/arch/microblaze/kernel/dma.c'

 /usr/local/elixir/query.py in query(cmd='file', *args=('v4.9.81', '/arch/microblaze/kernel/dma.c'))
  158                 tok2 = prefix + tok
  159                 if (even and db.defs.exists(tok2) and
  160                     (lib.compatibleFamily(db.defs.get(tok2).get_families(), family) or
  161                     lib.compatibleMacro(db.defs.get(tok2).get_macros(), family))):
  162                     tok = b'\033[31m' + tok2 + b'\033[0m'
global lib = <module 'lib' from '/usr/local/elixir/http/../lib.py'>
lib.compatibleFamily = <function compatibleFamily>
global db = <data.DB object>
db.defs = <data.BsdDB object>
db.defs.get = <bound method BsdDB.get of <data.BsdDB object>>
tok2 = b'EXPORT_SYMBOL'
).get_families undefined
family = 'C'
lib.compatibleMacro = <function compatibleMacro>
).get_macros undefined

 /usr/local/elixir/data.py in get(self=<data.BsdDB object>, key=b'EXPORT_SYMBOL')
  166         key = autoBytes(key)
  167         p = self.db.get(key)
  168         p = self.ctype(p)
  169         return p
  170
p = b'23210p847C,23210p848C,23210p849C,23210p850C,23...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
self = <data.BsdDB object>
self.ctype = <class 'data.DefList'>

 /usr/local/elixir/data.py in __init__(self=<data.DefList object>, data=b'23210p847C,23210p848C,23210p849C,23210p850C,23...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
   59         Also stores in which families the ident exists for faster tests.'''
   60     def __init__(self, data=b'#'):
   61         self.data, self.families = data.split(b'#')
   62
   63     def iter(self, dummy=False):
self = <data.DefList object>
self.data undefined
self.families undefined
data = b'23210p847C,23210p848C,23210p849C,23210p850C,23...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
data.split = <built-in method split of bytes object>
ValueError: too many values to unpack (expected 2)
    __cause__ = None
    __class__ = <class 'ValueError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of ValueError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of ValueError object>
    __doc__ = 'Inappropriate argument value (of correct type).'
    __eq__ = <method-wrapper '__eq__' of ValueError object>
    __format__ = <built-in method __format__ of ValueError object>
    __ge__ = <method-wrapper '__ge__' of ValueError object>
    __getattribute__ = <method-wrapper '__getattribute__' of ValueError object>
    __gt__ = <method-wrapper '__gt__' of ValueError object>
    __hash__ = <method-wrapper '__hash__' of ValueError object>
    __init__ = <method-wrapper '__init__' of ValueError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ValueError object>
    __lt__ = <method-wrapper '__lt__' of ValueError object>
    __ne__ = <method-wrapper '__ne__' of ValueError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ValueError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ValueError object>
    __repr__ = <method-wrapper '__repr__' of ValueError object>
    __setattr__ = <method-wrapper '__setattr__' of ValueError object>
    __setstate__ = <built-in method __setstate__ of ValueError object>
    __sizeof__ = <built-in method __sizeof__ of ValueError object>
    __str__ = <method-wrapper '__str__' of ValueError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('too many values to unpack (expected 2)',)
    with_traceback = <built-in method with_traceback of ValueError object>

Traceback (most recent call last):
  File "/usr/local/elixir/http/web.py", line 215, in <module>
    code = query('file', tag, path)
  File "/usr/local/elixir/http/../query.py", line 160, in query
    (lib.compatibleFamily(db.defs.get(tok2).get_families(), family) or
  File "/usr/local/elixir/http/../data.py", line 168, in get
    p = self.ctype(p)
  File "/usr/local/elixir/http/../data.py", line 61, in __init__
    self.data, self.families = data.split(b'#')
ValueError: too many values to unpack (expected 2)
```

**Comment by michaelopdenacker** [comment]
It seems we have this error on the server about 10-20 times per day.

**Comment by MaximeChretien** [comment]
There seems to be some problems in the way data are stored in the database, the presence of `\x00\x00\x00\x00\x00\x00` is quite strange.

I'll see if I'm able to reproduce this error and fix it.

**Comment by tpetazzoni** [comment]
Issue doesn't seem to appear anymore. @tleb will do some checking in the logs to make sure we no longer have other similar issues.

**Comment by tleb** [comment]
I can confirm the issue has not appeared in the last 10 days. We'll reopen if it reappears.
The error quoted above looks like a database corruption issue so it most probably has been regenerated since then.
