### ISSUE TITLE
Error while launching as normal user (permission denied)

### ISSUE THREAD

**Issue by Julius2238** [bootlin/elixir#230]
I just installed Exaile 4.1.2 as described [here](https://exaile.readthedocs.io/en/stable/user/install.html) on Trisquel 10. The installation completed. When in try to launch Exaile as a normal user, I get the following (where "Permission non accordée" means permission denied in french).

> julien@julien-Latitude-E7440:~/Téléchargements/exaile-4.1.2$ exaile
> 
> (exaile.py:25724): dbind-WARNING **: 20:21:13.400: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
> INFO    : Loading Exaile 4.1.2...
> INFO    : Using Python 3.8.10
> INFO    : Using PyGObject 3.36.0
> INFO    : Loading settings...
> INFO    : Using Locale fr_FR UTF-8
> INFO    : Using Mutagen 1.44.0
> INFO    : Using GStreamer 1.16.3
> INFO    : Reconfiguring crossfading
> INFO    : Crossfade: disabled
> INFO    : Using GTK+ 3.24.20
> INFO    : Using GTK+ theme Trisquel
> INFO    : Loading plugins...
> INFO    : Loading collection...
> ERROR   : Unhandled exception
> Traceback (most recent call last):
>   File "/usr/local/lib/exaile/xl/main.py", line 569, in __init__
>     self.__init()
>   File "/usr/local/lib/exaile/xl/main.py", line 672, in __init
>     self.collection = collection.Collection(
>   File "/usr/local/lib/exaile/xl/collection.py", line 143, in __init__
>     trax.TrackDB.__init__(self, name, location=location, pickle_attrs=pickle_attrs)
>   File "/usr/local/lib/exaile/xl/trax/trackdb.py", line 115, in __init__
>     self.load_from_location()
>   File "/usr/local/lib/exaile/xl/common.py", line 177, in wrapper
>     return func(self, *__args, **__kw)
>   File "/usr/local/lib/exaile/xl/trax/trackdb.py", line 186, in load_from_location
>     pdata = common.open_shelf(location)
>   File "/usr/local/lib/exaile/xl/common.py", line 416, in open_shelf
>     db = bsddb.hashopen(path, 'c')
>   File "/usr/lib/python3/dist-packages/bsddb3/__init__.py", line 335, in hashopen
>     d.open(file, db.DB_HASH, flags, mode)
> bsddb3.db.DBAccessError: (13, 'Permission non accordée')

Launching Exaile with `sudo exaile`, there is no problem.
Being a simple user, I can not find what file is problematic about the permission issue.
By the way, this seems to be a bug to me. So, I come here to tell about the problem.

**Comment by MaximeChretien** [comment]
Hello,

It seems like you didn't report your error in the good repository. This is Elixir Cross Referencer, not Exaile ;)
The Exaile repository can be found here : https://github.com/exaile/exaile

Have a nice day !

**Comment by fstachura** [comment]
Closing - the issue is not related to this project
