### ISSUE TITLE
Indexing issues with Linux project - database corruption

### ISSUE THREAD

**Issue by safinaskar** [bootlin/elixir#340]
Steps to reproduce:
- Open https://elixir.bootlin.com/linux/v6.11/C/ident/do_execveat_common

You will see `drivers/net/ethernet/mscc/ocelot_vcap.c, line 1898 (as a function)` in list of defines. But there is no line 1898 in this file

**Comment by fstachura** [comment]
Hello,

thank you for your report. We are currently investigating this issue. It's not yet entirely clear what caused it, but for now we have decided that we will reindex the whole Linux database - it seems that it somehow got corrupted. Reindexing should be done soon.
For now, if you don't need to browse *exactly* version 6.11, I suggest just switching Linux versions in the sidebar, it seems that other versions have correct results. (although it also seems that on v6.11 there are only extra bogus results, references in fs/exec.c are correct and are the only references I could find with grep).
It's also not clear to me yet if this is a problem with other identifiers too.

**Comment by fstachura** [comment]
Another set of identifiers with a similar issue - register_chrdev, register_chrdev_region. What's interesting is that both point to line ~2500 in  arch/loongarch/kvm/switch.S.

**Comment by tleb** [comment]
One more indexing issue: https://elixir.bootlin.com/linux/v6.12-rc1/A/ident/regulator_err2notif
We are missing two references, see [v6.11.2](https://elixir.bootlin.com/linux/v6.11.2/A/ident/regulator_err2notif) for example. Results should be almost exactly the same (not exact same line number).

This is the reverse of the `do_execveat_common()` bug: `do_execveat_common()` has ghost entries. `regulator_err2notif` is missing entries.

Let's keep track of all indexing issues without a clear root cause here. It might or might not be the same issue.

**Comment by fstachura** [comment]
It looks like no references were registered at all for https://elixir.bootlin.com/linux/v6.12-rc1/source/drivers/regulator/bd96801-regulator.c#L325
Open any identifier in a new tab and try to ctrl+f for the filename.
Maybe update was interrupted?

**Comment by Fomys** [comment]
Hi,
I just found another indexing issue: the documentations in this [file](https://elixir.bootlin.com/linux/v6.12-rc4/source/drivers/gpu/drm/display/drm_dp_mst_topology.c) are not indexed by elixir (at least the ~10 functions I checked).
For example, this [identifier](https://elixir.bootlin.com/linux/v6.12-rc4/C/ident/drm_dp_mst_hpd_irq_handle_event) has according to elixir:
- one prototype
- one definition
- two references
But I also expect to see the `documentation` item.

**Comment by Fomys** [comment]
[An other issue](https://elixir.bootlin.com/linux/v6.12-rc4/source/drivers/gpu/drm/i915/display/intel_dp.c#L6928) (very strange this time):
![image](https://github.com/user-attachments/assets/1c453ace-51ec-4dc9-a772-542bc66bf978)
The identifier have the <a> link, that seems to works (see screenshot), but as you can see, the reference is not [listed](https://elixir.bootlin.com/linux/v6.12-rc4/C/ident/intel_dp_mst_encoder_init)

**Comment by fstachura** [comment]
0b8d7356 introduces a bit more thread safety, which maybe will prevent that happening in the future to that extent. Depends on whether this happens because an actual race condition, or because the update process got interrupted. The next important step will be to make update process interruptable/restartable.

**Comment by Fomys** [comment]
Excellent news! Thank you for the investigation!

**Comment by tleb** [comment]
To keep this issue exhaustive, I'll describe here our best guess (with @fstachura) as to why some files are missing all their references:
 - `update.py` does a `./script.sh list-tags` to find all project tags ([ref](https://github.com/bootlin/elixir/blob/c54a4c3decbe564b5822625e7e2e9788c85f0472/update.py#L579)).
 - It runs the indexing on all tags that are not present in `versions.db` ([ref](https://github.com/bootlin/elixir/blob/c54a4c3decbe564b5822625e7e2e9788c85f0472/update.py#L580-L581)).
 - The first step of the indexing is to find all blobs. Once that is done, the version is added to `versions.db` ([ref](https://github.com/bootlin/elixir/blob/c54a4c3decbe564b5822625e7e2e9788c85f0472/update.py#L189)).

Now, if we imagine a crash by `update.py`: a version that did its first step has an entry in `versions.db`, but has not had the indexing of all its blobs done.

We have seen some crashes from `update.py`. Memory tells me it was OOM, but I am not sure.

**Comment by tleb** [comment]
Production database for Linux has been updated with a from-scratch indexing. All missing identifiers/references/docs listed above should now be present on https://elixir.bootlin.com/.

The bug is not fixed per-se, as it can reoccur if/when the indexing fails again.

**Comment by Fomys** [comment]
New bug:

Identifier properly identified: https://elixir.bootlin.com/linux/v6.12.5/source/kernel/bpf/syscall.c#L1398
But not displayed when showing the identifier usage: https://elixir.bootlin.com/linux/v6.12.5/C/ident/bpf_map_alloc_id

This seems to be fixed for v6.13

**Comment by tleb** [comment]
Cron job logs do contain an error, unsure if it is related:

```
Processing project /srv/elixir-data/linux ...
Fetching origin
From https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux
 * branch                      HEAD       -> FETCH_HEAD
 * [new tag]                   v6.13-rc3  -> v6.13-rc3
Fetching other
Fetching other2
Exception in thread UpdateRefsElixir:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/elixir/./update.py", line 282, in run
    self.update_references(new_idxes[self.index][0])
  File "/usr/local/elixir/./update.py", line 334, in update_references
    obj = db.refs.get(ident)
  File "/usr/local/elixir/elixir/data.py", line 167, in get
    p = self.db.get(key)
berkeleydb.db.DBPageNotFoundError: (-30986, 'BDB0075 DB_PAGE_NOTFOUND: Requested page not found')
linux - found 1 new tags
linux - ids: v6.13-rc3: 320 new blobs (100.0%)
linux - ids: Thread finished (100.0%)
linux - defs: Thread 1/2 finished (100.0%)
linux - refs: Thread 1/3 finished (0.0%)
linux - refs: Thread 2/3 finished (0.0%)
linux - comps: Thread 1/1 finished (100.0%)
linux - vers: v6.13-rc3 done (100.0%)
linux - vers: Thread finished (100.0%)
linux - comps_docs: Thread 1/1 finished (100.0%)
linux - docs: Thread 1/1 finished (100.0%)
linux - defs: Thread 2/2 finished (100.0%)
```

**Comment by tleb** [comment]
Our assumption was that all those identifier bugs were related to database corruptions. The good news is that those cannot happen anymore.

 - The HTTP server is one container that has the data mounted as read-only.
 - The indexing script is another container that has access to a copy of the data. If it succeeds, that new data is used for the HTTP server. If it ever fails, the corrupted data is ignored.
